language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: lk5sOGWmEGWHerSPY5QGjZPPTcNo3HokKpmiue7nAfgmwp2l/jvYQuvTCV639KcxegTzDfFR7nIheaw+tqHjudePnP4Py0yWEPduVZUI5Vbs6awyt8t7JcwTaWLQILTpSzjc4iXR6cTi/h+DUEjYRgxSbhPKk4IlBeRQ3FvTIAXoegZoTLjmBGR8b/Azs7DzU3fAntZnOK8PKRFj6U4ZsUJg6ESKLs0gPFMfgK7Q6STQ4T1qC1tlfCb2ToflILb2mcccwIGDtDSWQksnL4FS9EXTi0RaJ/DkWP1bctsvW9ACrvG0mjzZLSO0yQ5tua/Q0WgClU1C0bXikFOSPLBEP8Lec7Abhnd1P0xMEN/9lQ3JEj822eZayrqGpuxNPvGW5Mi6NESZyx4AJPNwwIAGwYibAV01bQj0dZLlvY8AcdbesYaQGf+opTaK0E6OoTxlzVverWDj/+O+OO4b0JvL+6GeP0ohhQkKhobW5Bh3gVbbLPX/VsIPoV66jAhFqLXA3h9OHILedorfh6UvkssOOzn/IuOJPKm0AhRnLSslNBTrvARDCOriz3wCs8DHF6IfCL9FILabkf3kqoVW8JbJ64PrPkGPxQoqxOF5jSDssjH7Fn6bCSX8yXluwt1cCUL42V8pLKng/1kHOOFSvVe57mcJM7jOQkdcZ5p9ediVYZ8=
    - M2_REPO: ~/.m2

install:
  - mvn dependency:resolve
script:
  - mvn test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
after_success:
  - openssl aes-256-cbc -K $encrypted_46b0bb06b333_key -iv $encrypted_46b0bb06b333_iv -in src/deploy/private.key.enc -out src/deploy/private.key -d
  - gpg --import src/deploy/private.key && gpg --import src/deploy/public.key
  - mkdir -p src/site/markdown && cp README.md src/site/markdown/index.md
  - mvn dependency:get -Dartifact=com.github.andreptb:andreptb-component-parent:0.2.1:xml:mvn-settings
  - mvn -s $M2_REPO/repository/com/github/andreptb/andreptb-component-parent/0.2.1/andreptb-component-parent-0.2.1-mvn-settings.xml -DskipTests -Dmaven.install.skip -DstagingDescription=$TRAVIS_COMMIT -Dgithub.global.oauth2Token=$GH_TOKEN deploy site-deploy
