language: java
env:
  matrix:
    secure: me+97cJ+o5hnp2GeSCqi3eowGKy4jy/GHkbLpVdSKwH9MOxAn2QnQTinlmbYnOSKi0mDndxAe27WZNPzfMDo7gK/TYZ52uHsMd2y2BUDEWidp1mzXToo2YSwyW5uCY1JtBc2fDv8yAphp1of/yCN3U1nKO7ztkTd6n0zOvKaxzhs0faVoDWETaTEN8l/xo0GLreW025IXY65ziZaBSc20xqyCGls+5dvEufJq+jTPCrET6OPiGX4fnwcxhRD/Vcn7+qbIu5DGMbZ3zs2rWEIOM4T3JuLgsJC/jnNWRN8qVnl+f+nEYlu2Vh1mtTBIGBnQ4cWSxLt6JOrIhnVTiAU3Es+ZDmayV7REGR/Exz507PvyYpVWk/YXprrsNQLsxSHnKPTvbHc4XvDsURLzf+SYatPw504MbTpqvBfIzGlrCTXRg5qMBXHWTJkbIJiv2tMTjG0/q/GH+2kmfUDCJwOtHyE7MJQ3dvSoyd8qrZN+L+W23QEzP6Nh0XFnmTbjwVTv2M/wQ7ZqrXWTPCJAD00KFVI1twVDb56ryNYtJQydQglhYFKSGlz0MbiJMbhT3M35gigYnspHDPtHyaZdikgw6id2VQQg2yApMZfUcneS6+7FfPp0Vw4CEun3T1ZE7kPUZyvTz+GE7HxgduFHfDrTAjKuoT4nVp2grPkWW0F1YY=
script:
- mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
